# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

java_test(
    name = "BlobStoreClientTest",
    srcs = ["BlobStoreClientTest.java"],
    deps = [
        "//java/com/google/cm/mrp/clients/blobstoreclient",
        "//java/external:clients_blobstorageclient",
        "//java/external:clients_blobstorageclient_model",
        "//java/external:gcp_storage",
        "//java/external:google_api_client",
        "//java/external:google_http_client",
        "//java/external:google_truth",
        "//java/external:guava",
        "//java/external:mockito",
        "//protos/mrp/backend:java_proto",
    ],
)
