/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef CC_MATCH_SERVICE_DATA_FORMAT_DETECTORS_CANONICAL_COUNTRIES_H_
#define CC_MATCH_SERVICE_DATA_FORMAT_DETECTORS_CANONICAL_COUNTRIES_H_
#include "absl/base/no_destructor.h"
#include "absl/container/flat_hash_map.h"
#include "absl/strings/string_view.h"

namespace google::confidential_match::match_service {

const absl::flat_hash_map<absl::string_view, absl::string_view>&
GetCanonicalCountriesMap() {
  static const absl::NoDestructor<
      absl::flat_hash_map<absl::string_view, absl::string_view>>
      canonical_countries_map(
          {{"aw", "aw"},
           {"af", "af"},
           {"ao", "ao"},
           {"ai", "ai"},
           {"ax", "ax"},
           {"al", "al"},
           {"ad", "ad"},
           {"ae", "ae"},
           {"ar", "ar"},
           {"am", "am"},
           {"an", "an"},
           {"as", "as"},
           {"aq", "aq"},
           {"tf", "tf"},
           {"ag", "ag"},
           {"au", "au"},
           {"at", "at"},
           {"az", "az"},
           {"bi", "bi"},
           {"be", "be"},
           {"bj", "bj"},
           {"bq", "bq"},
           {"bf", "bf"},
           {"bd", "bd"},
           {"bg", "bg"},
           {"bh", "bh"},
           {"bs", "bs"},
           {"ba", "ba"},
           {"bl", "bl"},
           {"by", "by"},
           {"bz", "bz"},
           {"bm", "bm"},
           {"bo", "bo"},
           {"br", "br"},
           {"bb", "bb"},
           {"bn", "bn"},
           {"bt", "bt"},
           {"bv", "bv"},
           {"bw", "bw"},
           {"cf", "cf"},
           {"ca", "ca"},
           {"cc", "cc"},
           {"ch", "ch"},
           {"cl", "cl"},
           {"cn", "cn"},
           {"ci", "ci"},
           {"cm", "cm"},
           {"cd", "cd"},
           {"cg", "cg"},
           {"ck", "ck"},
           {"co", "co"},
           {"km", "km"},
           {"cv", "cv"},
           {"cr", "cr"},
           {"cu", "cu"},
           {"cw", "cw"},
           {"cx", "cx"},
           {"ky", "ky"},
           {"cy", "cy"},
           {"cz", "cz"},
           {"de", "de"},
           {"dj", "dj"},
           {"dm", "dm"},
           {"dk", "dk"},
           {"do", "do"},
           {"dz", "dz"},
           {"ec", "ec"},
           {"eg", "eg"},
           {"er", "er"},
           {"eh", "eh"},
           {"es", "es"},
           {"ee", "ee"},
           {"et", "et"},
           {"fi", "fi"},
           {"fj", "fj"},
           {"fk", "fk"},
           {"fr", "fr"},
           {"fo", "fo"},
           {"fm", "fm"},
           {"ga", "ga"},
           {"gb", "gb"},
           {"ge", "ge"},
           {"gg", "gg"},
           {"gh", "gh"},
           {"gi", "gi"},
           {"gn", "gn"},
           {"gp", "gp"},
           {"gm", "gm"},
           {"gw", "gw"},
           {"gq", "gq"},
           {"gr", "gr"},
           {"gd", "gd"},
           {"gl", "gl"},
           {"gt", "gt"},
           {"gf", "gf"},
           {"gu", "gu"},
           {"gy", "gy"},
           {"hk", "hk"},
           {"hm", "hm"},
           {"hn", "hn"},
           {"hr", "hr"},
           {"ht", "ht"},
           {"hu", "hu"},
           {"id", "id"},
           {"im", "im"},
           {"in", "in"},
           {"io", "io"},
           {"ie", "ie"},
           {"ir", "ir"},
           {"iq", "iq"},
           {"is", "is"},
           {"il", "il"},
           {"it", "it"},
           {"jm", "jm"},
           {"ja", "jp"},
           {"je", "je"},
           {"jo", "jo"},
           {"jp", "jp"},
           {"kz", "kz"},
           {"ke", "ke"},
           {"kg", "kg"},
           {"kh", "kh"},
           {"ki", "ki"},
           {"kn", "kn"},
           {"kr", "kr"},
           {"kw", "kw"},
           {"la", "la"},
           {"lb", "lb"},
           {"lr", "lr"},
           {"ly", "ly"},
           {"lc", "lc"},
           {"li", "li"},
           {"lk", "lk"},
           {"ls", "ls"},
           {"lt", "lt"},
           {"lu", "lu"},
           {"lv", "lv"},
           {"mo", "mo"},
           {"mf", "mf"},
           {"ma", "ma"},
           {"mc", "mc"},
           {"md", "md"},
           {"mg", "mg"},
           {"mv", "mv"},
           {"mx", "mx"},
           {"mh", "mh"},
           {"mk", "mk"},
           {"ml", "ml"},
           {"mt", "mt"},
           {"mm", "mm"},
           {"me", "me"},
           {"mn", "mn"},
           {"mp", "mp"},
           {"mz", "mz"},
           {"mr", "mr"},
           {"ms", "ms"},
           {"mq", "mq"},
           {"mu", "mu"},
           {"mw", "mw"},
           {"my", "my"},
           {"yt", "yt"},
           {"na", "na"},
           {"nc", "nc"},
           {"ne", "ne"},
           {"nf", "nf"},
           {"ng", "ng"},
           {"ni", "ni"},
           {"nu", "nu"},
           {"nl", "nl"},
           {"no", "no"},
           {"np", "np"},
           {"nr", "nr"},
           {"nz", "nz"},
           {"om", "om"},
           {"pk", "pk"},
           {"pa", "pa"},
           {"pn", "pn"},
           {"pe", "pe"},
           {"ph", "ph"},
           {"pw", "pw"},
           {"pg", "pg"},
           {"pl", "pl"},
           {"pr", "pr"},
           {"kp", "kp"},
           {"pt", "pt"},
           {"py", "py"},
           {"ps", "ps"},
           {"pf", "pf"},
           {"qa", "qa"},
           {"re", "re"},
           {"ro", "ro"},
           {"ru", "ru"},
           {"rw", "rw"},
           {"sa", "sa"},
           {"sd", "sd"},
           {"sn", "sn"},
           {"sg", "sg"},
           {"gs", "gs"},
           {"sh", "sh"},
           {"sj", "sj"},
           {"sb", "sb"},
           {"sl", "sl"},
           {"sv", "sv"},
           {"sm", "sm"},
           {"so", "so"},
           {"pm", "pm"},
           {"rs", "rs"},
           {"ss", "ss"},
           {"st", "st"},
           {"sr", "sr"},
           {"sk", "sk"},
           {"si", "si"},
           {"se", "se"},
           {"sz", "sz"},
           {"sx", "sx"},
           {"sc", "sc"},
           {"sy", "sy"},
           {"tc", "tc"},
           {"td", "td"},
           {"tg", "tg"},
           {"th", "th"},
           {"tj", "tj"},
           {"tk", "tk"},
           {"tm", "tm"},
           {"tl", "tl"},
           {"to", "to"},
           {"tt", "tt"},
           {"tn", "tn"},
           {"tr", "tr"},
           {"tv", "tv"},
           {"tw", "tw"},
           {"tz", "tz"},
           {"ug", "ug"},
           {"ua", "ua"},
           {"um", "um"},
           {"uy", "uy"},
           {"us", "us"},
           {"uz", "uz"},
           {"va", "va"},
           {"vc", "vc"},
           {"ve", "ve"},
           {"vg", "vg"},
           {"vi", "vi"},
           {"vn", "vn"},
           {"vu", "vu"},
           {"wf", "wf"},
           {"ws", "ws"},
           {"xk", "xk"},
           {"ye", "ye"},
           {"za", "za"},
           {"zm", "zm"},
           {"zw", "zw"},
           {"abw", "aw"},
           {"afg", "af"},
           {"ago", "ao"},
           {"aia", "ai"},
           {"ala", "ax"},
           {"alb", "al"},
           {"and", "ad"},
           {"are", "ae"},
           {"arg", "ar"},
           {"arm", "am"},
           {"asm", "as"},
           {"ata", "aq"},
           {"atf", "tf"},
           {"atg", "ag"},
           {"aus", "au"},
           {"aut", "at"},
           {"aze", "az"},
           {"bdi", "bi"},
           {"bel", "be"},
           {"ben", "bj"},
           {"bes", "bq"},
           {"bfa", "bf"},
           {"bgd", "bd"},
           {"bgr", "bg"},
           {"bhr", "bh"},
           {"bhs", "bs"},
           {"bih", "ba"},
           {"blm", "bl"},
           {"blr", "by"},
           {"blz", "bz"},
           {"bmu", "bm"},
           {"bol", "bo"},
           {"bra", "br"},
           {"brb", "bb"},
           {"brn", "bn"},
           {"btn", "bt"},
           {"bvt", "bv"},
           {"bwa", "bw"},
           {"caf", "cf"},
           {"can", "ca"},
           {"cck", "cc"},
           {"che", "ch"},
           {"chl", "cl"},
           {"chn", "cn"},
           {"civ", "ci"},
           {"cmr", "cm"},
           {"cod", "cd"},
           {"cog", "cg"},
           {"cok", "ck"},
           {"col", "co"},
           {"com", "km"},
           {"cpv", "cv"},
           {"cri", "cr"},
           {"cub", "cu"},
           {"cuw", "cw"},
           {"cxr", "cx"},
           {"cym", "ky"},
           {"cyp", "cy"},
           {"cze", "cz"},
           {"deu", "de"},
           {"dji", "dj"},
           {"dma", "dm"},
           {"dnk", "dk"},
           {"dom", "do"},
           {"dza", "dz"},
           {"ecu", "ec"},
           {"egy", "eg"},
           {"eri", "er"},
           {"esh", "eh"},
           {"esp", "es"},
           {"est", "ee"},
           {"eth", "et"},
           {"fin", "fi"},
           {"fji", "fj"},
           {"flk", "fk"},
           {"fra", "fr"},
           {"fro", "fo"},
           {"fsm", "fm"},
           {"gab", "ga"},
           {"gbr", "gb"},
           {"geo", "ge"},
           {"ggy", "gg"},
           {"gha", "gh"},
           {"gib", "gi"},
           {"gin", "gn"},
           {"glp", "gp"},
           {"gmb", "gm"},
           {"gnb", "gw"},
           {"gnq", "gq"},
           {"grc", "gr"},
           {"grd", "gd"},
           {"grl", "gl"},
           {"gtm", "gt"},
           {"guf", "gf"},
           {"gum", "gu"},
           {"guy", "gy"},
           {"hkg", "hk"},
           {"hmd", "hm"},
           {"hnd", "hn"},
           {"hrv", "hr"},
           {"hti", "ht"},
           {"hun", "hu"},
           {"idn", "id"},
           {"imn", "im"},
           {"ind", "in"},
           {"iot", "io"},
           {"irl", "ie"},
           {"irn", "ir"},
           {"irq", "iq"},
           {"isl", "is"},
           {"isr", "il"},
           {"ita", "it"},
           {"jam", "jm"},
           {"jey", "je"},
           {"jor", "jo"},
           {"jpn", "jp"},
           {"kaz", "kz"},
           {"ken", "ke"},
           {"kgz", "kg"},
           {"khm", "kh"},
           {"kir", "ki"},
           {"kna", "kn"},
           {"kor", "kr"},
           {"kwt", "kw"},
           {"lao", "la"},
           {"lbn", "lb"},
           {"lbr", "lr"},
           {"lby", "ly"},
           {"lca", "lc"},
           {"lie", "li"},
           {"lka", "lk"},
           {"lso", "ls"},
           {"ltu", "lt"},
           {"lux", "lu"},
           {"lva", "lv"},
           {"mac", "mo"},
           {"maf", "mf"},
           {"mar", "ma"},
           {"mco", "mc"},
           {"mda", "md"},
           {"mdg", "mg"},
           {"mdv", "mv"},
           {"mex", "mx"},
           {"mhl", "mh"},
           {"mkd", "mk"},
           {"mli", "ml"},
           {"mlt", "mt"},
           {"mmr", "mm"},
           {"mne", "me"},
           {"mng", "mn"},
           {"mnp", "mp"},
           {"moz", "mz"},
           {"mrt", "mr"},
           {"msr", "ms"},
           {"mtq", "mq"},
           {"mus", "mu"},
           {"mwi", "mw"},
           {"mys", "my"},
           {"myt", "yt"},
           {"nam", "na"},
           {"ncl", "nc"},
           {"ner", "ne"},
           {"nfk", "nf"},
           {"nga", "ng"},
           {"nic", "ni"},
           {"niu", "nu"},
           {"nld", "nl"},
           {"nor", "no"},
           {"npl", "np"},
           {"nru", "nr"},
           {"nzl", "nz"},
           {"omn", "om"},
           {"pak", "pk"},
           {"pan", "pa"},
           {"pcn", "pn"},
           {"per", "pe"},
           {"phl", "ph"},
           {"plw", "pw"},
           {"png", "pg"},
           {"pol", "pl"},
           {"pri", "pr"},
           {"prk", "kp"},
           {"prt", "pt"},
           {"pry", "py"},
           {"pse", "ps"},
           {"pyf", "pf"},
           {"qat", "qa"},
           {"reu", "re"},
           {"rou", "ro"},
           {"rus", "ru"},
           {"rwa", "rw"},
           {"sau", "sa"},
           {"sdn", "sd"},
           {"sen", "sn"},
           {"sgp", "sg"},
           {"sgs", "gs"},
           {"shn", "sh"},
           {"sjm", "sj"},
           {"slb", "sb"},
           {"sle", "sl"},
           {"slv", "sv"},
           {"smr", "sm"},
           {"som", "so"},
           {"spm", "pm"},
           {"srb", "rs"},
           {"ssd", "ss"},
           {"stp", "st"},
           {"sur", "sr"},
           {"svk", "sk"},
           {"svn", "si"},
           {"swe", "se"},
           {"swz", "sz"},
           {"sxm", "sx"},
           {"syc", "sc"},
           {"syr", "sy"},
           {"tca", "tc"},
           {"tcd", "td"},
           {"tgo", "tg"},
           {"tha", "th"},
           {"tjk", "tj"},
           {"tkl", "tk"},
           {"tkm", "tm"},
           {"tls", "tl"},
           {"ton", "to"},
           {"tto", "tt"},
           {"tun", "tn"},
           {"tur", "tr"},
           {"tuv", "tv"},
           {"twn", "tw"},
           {"tza", "tz"},
           {"uga", "ug"},
           {"ukr", "ua"},
           {"umi", "um"},
           {"ury", "uy"},
           {"usa", "us"},
           {"uzb", "uz"},
           {"vat", "va"},
           {"vct", "vc"},
           {"ven", "ve"},
           {"vgb", "vg"},
           {"vir", "vi"},
           {"vnm", "vn"},
           {"vut", "vu"},
           {"wlf", "wf"},
           {"wsm", "ws"},
           {"yem", "ye"},
           {"xkx", "xk"},
           {"zaf", "za"},
           {"zmb", "zm"},
           {"zwe", "zw"},
           {"afghanistan", "af"},
           {"akrotiri", "gb"},
           {"åland", "ax"},
           {"åland islands", "ax"},
           {"albania", "al"},
           {"algeria", "dz"},
           {"allemagne", "de"},
           {"american samoa", "as"},
           {"andorra", "ad"},
           {"angola", "ao"},
           {"anguilla", "ai"},
           {"antarctica", "aq"},
           {"antigua", "ag"},
           {"antigua and barbuda", "ag"},
           {"argentina", "ar"},
           {"armenia", "am"},
           {"aruba", "aw"},
           {"ascension island", "sh"},
           {"ashmore and cartier islands", "au"},
           {"ashmore island", "au"},
           {"australia", "au"},
           {"austria", "at"},
           {"azerbaijan", "az"},
           {"bahamas", "bs"},
           {"bahrain", "bh"},
           {"bangladesh", "bd"},
           {"barbados", "bb"},
           {"barbuda", "ag"},
           {"belarus", "by"},
           {"belgium", "be"},
           {"belgië", "be"},
           {"belize", "bz"},
           {"benin", "bj"},
           {"bermuda", "bm"},
           {"bhutan", "bt"},
           {"bolivia", "bo"},
           {"bonaire", "bq"},
           {"bonaire, sint eustatius and saba", "bq"},
           {"bosnia", "ba"},
           {"bosnia and herzegovina", "ba"},
           {"botswana", "bw"},
           {"bouvet island", "bv"},
           {"brasil", "br"},
           {"brazil", "br"},
           {"british indian ocean territory", "io"},
           {"british virgin islands", "vg"},
           {"brunei", "bn"},
           {"brunei darussalam", "bn"},
           {"bulgaria", "bg"},
           {"burkina faso", "bf"},
           {"burma", "mm"},
           {"burundi", "bi"},
           {"cabo verde", "cv"},
           {"caicos islands", "tc"},
           {"cambodia", "kh"},
           {"cameroon", "cm"},
           {"canada", "ca"},
           {"cape verde", "cv"},
           {"caribbean netherlands", "bq"},
           {"cartier island", "au"},
           {"cayman islands", "ky"},
           {"central african republic", "cf"},
           {"chad", "td"},
           {"chile", "cl"},
           {"china", "cn"},
           {"china, people's republic of", "cn"},
           {"christmas island", "cx"},
           {"clipperton island", "fr"},
           {"cocos (keeling) islands", "cc"},
           {"cocos islands", "cc"},
           {"colombia", "co"},
           {"comoros", "km"},
           {"congo", "cg"},
           {"congo republic", "cg"},
           {"congo, democratic republic", "cd"},
           {"cook islands", "ck"},
           {"coral sea islands", "au"},
           {"costa rica", "cr"},
           {"cote d'ivoire", "ci"},
           {"côte d'ivoire", "ci"},
           {"croatia", "hr"},
           {"cuba", "cu"},
           {"curacao", "cw"},
           {"curaçao", "cw"},
           {"cyprus", "cy"},
           {"czech republic", "cz"},
           {"czechia", "cz"},
           {"Česká republika", "cz"},
           {"democratic people's republic of korea", "kp"},
           {"democratic republic of the congo", "cd"},
           {"denmark", "dk"},
           {"deutschland", "de"},
           {"dhekelia", "gb"},
           {"djibouti", "dj"},
           {"dominica", "dm"},
           {"dominican republic", "do"},
           {"east congo", "cd"},
           {"east timor", "tl"},
           {"ecuador", "ec"},
           {"egypt", "eg"},
           {"el salvador", "sv"},
           {"emirates", "ae"},
           {"england", "gb"},
           {"equatorial guinea", "gq"},
           {"eritrea", "er"},
           {"espanya", "es"},
           {"espaÑa", "es"},
           {"españa", "es"},
           {"estados unidos", "us"},
           {"estonia", "ee"},
           {"eswatini", "sz"},
           {"ethiopia", "et"},
           {"falkland islands", "fk"},
           {"falkland islands (malvinas)", "fk"},
           {"faroe islands", "fo"},
           {"fiji", "fj"},
           {"finland", "fi"},
           {"france", "fr"},
           {"french guiana", "gf"},
           {"french polynesia", "pf"},
           {"french southern territories", "tf"},
           {"futuna", "wf"},
           {"gabon", "ga"},
           {"gambia", "gm"},
           {"georgia", "ge"},
           {"germany", "de"},
           {"ghana", "gh"},
           {"gibraltar", "gi"},
           {"great britain", "gb"},
           {"greece", "gr"},
           {"greenland", "gl"},
           {"grenada", "gd"},
           {"guadeloupe", "gp"},
           {"guam", "gu"},
           {"guatemala", "gt"},
           {"guernsey", "gg"},
           {"guinea", "gn"},
           {"guinea-bissau", "gw"},
           {"guyana", "gy"},
           {"haiti", "ht"},
           {"hawaiian islands", "us"},
           {"heard and mcdonald islands", "hm"},
           {"heard island", "hm"},
           {"heard island and mcdonald islands", "hm"},
           {"herzegovina", "ba"},
           {"holy see", "va"},
           {"honduras", "hn"},
           {"hong kong", "hk"},
           {"hrvatska", "hr"},
           {"hungary", "hu"},
           {"iceland", "is"},
           {"india", "in"},
           {"indonesia", "id"},
           {"iran", "ir"},
           {"iraq", "iq"},
           {"ireland", "ie"},
           {"isle of man", "im"},
           {"israel", "il"},
           {"italia", "it"},
           {"italy", "it"},
           {"ivory coast", "ci"},
           {"jamaica", "jm"},
           {"jan mayen", "sj"},
           {"japan", "jp"},
           {"jersey", "je"},
           {"jordan", "jo"},
           {"kazakhstan", "kz"},
           {"keeling islands", "cc"},
           {"kenya", "ke"},
           {"kiribati", "ki"},
           {"korea, republic of", "kr"},
           {"kosovo", "xk"},
           {"kuwait", "kw"},
           {"kyrgyzstan", "kg"},
           {"lao people's democratic republic", "la"},
           {"laos", "la"},
           {"latvia", "lv"},
           {"lebanon", "lb"},
           {"lesotho", "ls"},
           {"liberia", "lr"},
           {"libya", "ly"},
           {"liechtenstein", "li"},
           {"lithuania", "lt"},
           {"luxembourg", "lu"},
           {"macao", "mo"},
           {"macau", "mo"},
           {"macedonia", "mk"},
           {"madagascar", "mg"},
           {"magyarország", "hu"},
           {"malawi", "mw"},
           {"malaysia", "my"},
           {"maldives", "mv"},
           {"mali", "ml"},
           {"malta", "mt"},
           {"malvinas", "fk"},
           {"marshall islands", "mh"},
           {"martinique", "mq"},
           {"mauritania", "mr"},
           {"mauritius", "mu"},
           {"mayotte", "yt"},
           {"mcdonald islands", "hm"},
           {"mexico", "mx"},
           {"mÉxico", "mx"},
           {"méxico", "mx"},
           {"micronesia", "fm"},
           {"moldova", "md"},
           {"monaco", "mc"},
           {"mongolia", "mn"},
           {"montenegro", "me"},
           {"montserrat", "ms"},
           {"morocco", "ma"},
           {"mozambique", "mz"},
           {"myanmar", "mm"},
           {"namibia", "na"},
           {"nauru", "nr"},
           {"nederland", "nl"},
           {"nepal", "np"},
           {"netherlands", "nl"},
           {"netherlands antilles", "an"},
           {"new caledonia", "nc"},
           {"new zealand", "nz"},
           {"nicaragua", "ni"},
           {"niger", "ne"},
           {"nigeria", "ng"},
           {"niue", "nu"},
           {"norfolk island", "nf"},
           {"north korea", "kp"},
           {"north macedonia", "mk"},
           {"northern ireland", "gb"},
           {"northern mariana islands", "mp"},
           {"norway", "no"},
           {"oman", "om"},
           {"Österreich", "at"},
           {"pakistan", "pk"},
           {"palau", "pw"},
           {"palestine", "ps"},
           {"palestinian territory", "ps"},
           {"panama", "pa"},
           {"papua new guinea", "pg"},
           {"paraguay", "py"},
           {"people's republic of china", "cn"},
           {"peru", "pe"},
           {"perÚ", "pe"},
           {"perú", "pe"},
           {"philippines", "ph"},
           {"pitcairn", "pn"},
           {"pitcairn islands", "pn"},
           {"poland", "pl"},
           {"polska", "pl"},
           {"portugal", "pt"},
           {"puerto rico", "pr"},
           {"qatar", "qa"},
           {"republic of china", "tw"},
           {"republic of korea", "kr"},
           {"republic of kosovo", "xk"},
           {"reunion", "re"},
           {"réunion", "re"},
           {"romania", "ro"},
           {"russia", "ru"},
           {"russian federation", "ru"},
           {"rwanda", "rw"},
           {"saba", "bq"},
           {"sahrawi arab democratic republic", "eh"},
           {"saint barthélemy", "bl"},
           {"saint helena", "sh"},
           {"saint kitts and nevis", "kn"},
           {"saint lucia", "lc"},
           {"saint martin", "mf"},
           {"saint pierre and miquelon", "pm"},
           {"saint vincent and the grenadines", "vc"},
           {"samoa", "ws"},
           {"san marino", "sm"},
           {"sao tome and principe", "st"},
           {"saudi arabia", "sa"},
           {"scotland", "gb"},
           {"senegal", "sn"},
           {"serbia", "rs"},
           {"seychelles", "sc"},
           {"sierra leone", "sl"},
           {"singapore", "sg"},
           {"sint eustatius", "bq"},
           {"sint maarten", "sx"},
           {"sint maarten (dutch part)", "sx"},
           {"slovakia", "sk"},
           {"slovenia", "si"},
           {"solomon islands", "sb"},
           {"somalia", "so"},
           {"south africa", "za"},
           {"south georgia and the south sandwich islands", "gs"},
           {"south korea", "kr"},
           {"south sudan", "ss"},
           {"spain", "es"},
           {"spanien", "es"},
           {"sri lanka", "lk"},
           {"st. helena", "sh"},
           {"st. pierre and miquelon", "pm"},
           {"sudan", "sd"},
           {"suriname", "sr"},
           {"svalbard", "sj"},
           {"svalbard and jan mayen islands", "sj"},
           {"svizzera", "ch"},
           {"swaziland", "sz"},
           {"sweden", "se"},
           {"switzerland", "ch"},
           {"syria", "sy"},
           {"syrian arab republic", "sy"},
           {"taiwan", "tw"},
           {"tajikistan", "tj"},
           {"tanzania", "tz"},
           {"thailand", "th"},
           {"the netherlands", "nl"},
           {"the united states of america", "us"},
           {"timor-leste", "tl"},
           {"tobago", "tt"},
           {"togo", "tg"},
           {"tokelau", "tk"},
           {"tonga", "to"},
           {"trinidad", "tt"},
           {"trinidad and tobago", "tt"},
           {"tristan da cunha", "sh"},
           {"tunisia", "tn"},
           {"turkey", "tr"},
           {"turkmenistan", "tm"},
           {"turks and caicos islands", "tc"},
           {"turks islands", "tc"},
           {"turquÍa", "tr"},
           {"tuvalu", "tv"},
           {"uae", "ae"},
           {"uganda", "ug"},
           {"uk", "gb"},
           {"ukraine", "ua"},
           {"united arab emirates", "ae"},
           {"united kingdom", "gb"},
           {"united kingdom of great britain and northern ireland", "gb"},
           {"united states", "us"},
           {"united states minor outlying islands", "um"},
           {"united states of america", "us"},
           {"united states virgin islands", "vi"},
           {"uruguay", "uy"},
           {"us virgin islands", "vi"},
           {"uzbekistan", "uz"},
           {"vanuatu", "vu"},
           {"vatican", "va"},
           {"vatican city", "va"},
           {"venezuela", "ve"},
           {"vereinigte staaten", "us"},
           {"viet nam", "vn"},
           {"vietnam", "vn"},
           {"virgin islands (british)", "vg"},
           {"virgin islands (u.s.)", "vi"},
           {"wales", "gb"},
           {"wallis", "wf"},
           {"wallis and futuna", "wf"},
           {"wallis and futuna islands", "wf"},
           {"west congo", "cg"},
           {"western sahara", "eh"},
           {"yemen", "ye"},
           {"zambia", "zm"},
           {"zimbabwe", "zw"},
           {"中国", "cn"},
           {"ไทย", "th"},
           {"Россия", "ru"}});
  return *canonical_countries_map;
}  // NOLINT(readability/fn_size)
}  // namespace google::confidential_match::match_service

#endif  // CC_MATCH_SERVICE_DATA_FORMAT_DETECTORS_CANONICAL_COUNTRIES_H_
